// console.log(process.env)
const {
  PORT,
  BCRYPT_SALT,
  MONGODB_URI,
  NEXTAUTH_JWT_SECRET,
  NEXT_PUBLIC_COMPANY_NAME,
  NEXTAUTH_URL,
  JWT_SECRET,
  STUDENT_REPORT_URL,
  NEXT_PUBLIC_STUDENT_REPORT_URL,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_UPLOAD_PRESET,
} = process.env;

const requiredCredentials = [
  "BCRYPT_SALT",
  "MONGODB_URI",
  "NEXTAUTH_JWT_SECRET",
  "NEXT_PUBLIC_COMPANY_NAME",
  "NEXTAUTH_URL",
  "JWT_SECRET",
  "STUDENT_REPORT_URL",
  "NEXT_PUBLIC_STUDENT_REPORT_URL",
  "CLOUDINARY_CLOUD_NAME",
  "CLOUDINARY_API_KEY",
  "CLOUDINARY_API_SECRET",
  "CLOUDINARY_UPLOAD_PRESET",
];

for (const credential of requiredCredentials) {
  if (process.env[credential] === undefined) {
    console.log(`Missing required crendential: ${credential}`);
    process.exit(1);
  }
}

export {
  PORT,
  BCRYPT_SALT,
  MONGODB_URI,
  NEXTAUTH_JWT_SECRET,
  NEXT_PUBLIC_COMPANY_NAME,
  NEXTAUTH_URL,
  JWT_SECRET,
  STUDENT_REPORT_URL,
  NEXT_PUBLIC_STUDENT_REPORT_URL,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_UPLOAD_PRESET,
};
